/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DashboardLayoutAlunosIndexRouteImport } from './routes/dashboard/_layout.alunos/index'
import { Route as DashboardLayoutContatosIndexRouteImport } from './routes/dashboard/_layout.contatos/index'
import { Route as DashboardLayoutConvitesIndexRouteImport } from './routes/dashboard/_layout.convites/index'
import { Route as DashboardLayoutFuncionariosIndexRouteImport } from './routes/dashboard/_layout.funcionarios/index'
import { Route as DashboardLayoutMusicosIndexRouteImport } from './routes/dashboard/_layout.musicos/index'
import { Route as DashboardLayoutPapeisIndexRouteImport } from './routes/dashboard/_layout.papeis/index'
import { Route as DashboardLayoutProfessoresIndexRouteImport } from './routes/dashboard/_layout.professores/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutAlunosIndexRoute =
  DashboardLayoutAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutContatosIndexRoute =
  DashboardLayoutContatosIndexRouteImport.update({
    id: '/contatos/',
    path: '/contatos/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutConvitesIndexRoute =
  DashboardLayoutConvitesIndexRouteImport.update({
    id: '/convites/',
    path: '/convites/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutFuncionariosIndexRoute =
  DashboardLayoutFuncionariosIndexRouteImport.update({
    id: '/funcionarios/',
    path: '/funcionarios/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutMusicosIndexRoute =
  DashboardLayoutMusicosIndexRouteImport.update({
    id: '/musicos/',
    path: '/musicos/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPapeisIndexRoute =
  DashboardLayoutPapeisIndexRouteImport.update({
    id: '/papeis/',
    path: '/papeis/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutProfessoresIndexRoute =
  DashboardLayoutProfessoresIndexRouteImport.update({
    id: '/professores/',
    path: '/professores/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/alunos/': typeof DashboardLayoutAlunosIndexRoute
  '/dashboard/contatos/': typeof DashboardLayoutContatosIndexRoute
  '/dashboard/convites/': typeof DashboardLayoutConvitesIndexRoute
  '/dashboard/funcionarios/': typeof DashboardLayoutFuncionariosIndexRoute
  '/dashboard/musicos/': typeof DashboardLayoutMusicosIndexRoute
  '/dashboard/papeis/': typeof DashboardLayoutPapeisIndexRoute
  '/dashboard/professores/': typeof DashboardLayoutProfessoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/alunos': typeof DashboardLayoutAlunosIndexRoute
  '/dashboard/contatos': typeof DashboardLayoutContatosIndexRoute
  '/dashboard/convites': typeof DashboardLayoutConvitesIndexRoute
  '/dashboard/funcionarios': typeof DashboardLayoutFuncionariosIndexRoute
  '/dashboard/musicos': typeof DashboardLayoutMusicosIndexRoute
  '/dashboard/papeis': typeof DashboardLayoutPapeisIndexRoute
  '/dashboard/professores': typeof DashboardLayoutProfessoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/_layout/alunos/': typeof DashboardLayoutAlunosIndexRoute
  '/dashboard/_layout/contatos/': typeof DashboardLayoutContatosIndexRoute
  '/dashboard/_layout/convites/': typeof DashboardLayoutConvitesIndexRoute
  '/dashboard/_layout/funcionarios/': typeof DashboardLayoutFuncionariosIndexRoute
  '/dashboard/_layout/musicos/': typeof DashboardLayoutMusicosIndexRoute
  '/dashboard/_layout/papeis/': typeof DashboardLayoutPapeisIndexRoute
  '/dashboard/_layout/professores/': typeof DashboardLayoutProfessoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login/'
    | '/profile/'
    | '/dashboard/alunos/'
    | '/dashboard/contatos/'
    | '/dashboard/convites/'
    | '/dashboard/funcionarios/'
    | '/dashboard/musicos/'
    | '/dashboard/papeis/'
    | '/dashboard/professores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/dashboard/alunos'
    | '/dashboard/contatos'
    | '/dashboard/convites'
    | '/dashboard/funcionarios'
    | '/dashboard/musicos'
    | '/dashboard/papeis'
    | '/dashboard/professores'
  id:
    | '__root__'
    | '/'
    | '/dashboard/_layout'
    | '/login/'
    | '/profile/'
    | '/dashboard/_layout/alunos/'
    | '/dashboard/_layout/contatos/'
    | '/dashboard/_layout/convites/'
    | '/dashboard/_layout/funcionarios/'
    | '/dashboard/_layout/musicos/'
    | '/dashboard/_layout/papeis/'
    | '/dashboard/_layout/professores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/alunos/': {
      id: '/dashboard/_layout/alunos/'
      path: '/alunos'
      fullPath: '/dashboard/alunos/'
      preLoaderRoute: typeof DashboardLayoutAlunosIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/contatos/': {
      id: '/dashboard/_layout/contatos/'
      path: '/contatos'
      fullPath: '/dashboard/contatos/'
      preLoaderRoute: typeof DashboardLayoutContatosIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/convites/': {
      id: '/dashboard/_layout/convites/'
      path: '/convites'
      fullPath: '/dashboard/convites/'
      preLoaderRoute: typeof DashboardLayoutConvitesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/funcionarios/': {
      id: '/dashboard/_layout/funcionarios/'
      path: '/funcionarios'
      fullPath: '/dashboard/funcionarios/'
      preLoaderRoute: typeof DashboardLayoutFuncionariosIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/musicos/': {
      id: '/dashboard/_layout/musicos/'
      path: '/musicos'
      fullPath: '/dashboard/musicos/'
      preLoaderRoute: typeof DashboardLayoutMusicosIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/papeis/': {
      id: '/dashboard/_layout/papeis/'
      path: '/papeis'
      fullPath: '/dashboard/papeis/'
      preLoaderRoute: typeof DashboardLayoutPapeisIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/professores/': {
      id: '/dashboard/_layout/professores/'
      path: '/professores'
      fullPath: '/dashboard/professores/'
      preLoaderRoute: typeof DashboardLayoutProfessoresIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutAlunosIndexRoute: typeof DashboardLayoutAlunosIndexRoute
  DashboardLayoutContatosIndexRoute: typeof DashboardLayoutContatosIndexRoute
  DashboardLayoutConvitesIndexRoute: typeof DashboardLayoutConvitesIndexRoute
  DashboardLayoutFuncionariosIndexRoute: typeof DashboardLayoutFuncionariosIndexRoute
  DashboardLayoutMusicosIndexRoute: typeof DashboardLayoutMusicosIndexRoute
  DashboardLayoutPapeisIndexRoute: typeof DashboardLayoutPapeisIndexRoute
  DashboardLayoutProfessoresIndexRoute: typeof DashboardLayoutProfessoresIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutAlunosIndexRoute: DashboardLayoutAlunosIndexRoute,
  DashboardLayoutContatosIndexRoute: DashboardLayoutContatosIndexRoute,
  DashboardLayoutConvitesIndexRoute: DashboardLayoutConvitesIndexRoute,
  DashboardLayoutFuncionariosIndexRoute: DashboardLayoutFuncionariosIndexRoute,
  DashboardLayoutMusicosIndexRoute: DashboardLayoutMusicosIndexRoute,
  DashboardLayoutPapeisIndexRoute: DashboardLayoutPapeisIndexRoute,
  DashboardLayoutProfessoresIndexRoute: DashboardLayoutProfessoresIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
