
-- ==========================================================================================
-- TABELAS DE MEMBROS, ALUNO, PROFESSOR, FUNCIONARIOS, MUSICOS E SUAS CREDENCIAIS DE ACESSO
-- ==========================================================================================

CREATE TYPE tipo_sexo_pessoa AS ENUM ('MASCULINO', 'FEMININO', 'NAO INFORMADO');

-- Tabela principal de membros
CREATE TABLE IF NOT EXISTS membro (
    id UUID PRIMARY KEY,
    nome_legal VARCHAR(72) NOT NULL,
    data_nascimento DATE NOT NULL,
    sexo tipo_sexo_pessoa NOT NULL DEFAULT 'NAO INFORMADO',
    endereco VARCHAR(256),
    telefone VARCHAR(15),
    email VARCHAR(256) UNIQUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- status_membro_credencial ENUM
-- Inativo = Quando um membro saiu da organização
-- Ativo = Quando o membro esta ativo e exercendo função na organização
-- Bloqueado = Quando o membro foi bloqueado por ações não favoraveis

CREATE TYPE status_membro_credencial AS ENUM ('ATIVO','INATIVO','BLOQUEADO');

-- Tabela de credenciais de acesso (senha)
CREATE TABLE IF NOT EXISTS membro_credencial (
    id_membro UUID PRIMARY KEY,
    nome_usuario VARCHAR(32) UNIQUE,
    hash_password VARCHAR(256) NOT NULL,
    status status_membro_credencial NOT NULL DEFAULT 'ATIVO',
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_membro) REFERENCES membro(id)
);

CREATE TYPE tipo_funcao AS ENUM ('SISTEMA', 'DOMINIO');

CREATE TABLE IF NOT EXISTS funcao (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(32) NOT NULL,
    nome VARCHAR(64) NOT NULL,
    descricao TEXT,
    tipo tipo_funcao NOT NULL,

    CONSTRAINT idx_unique_code UNIQUE (code),
    CONSTRAINT pk_funcao PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS membro_vinculo (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_funcao INT NOT NULL,
    id_membro UUID NOT NULL,

    data_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_termino TIMESTAMP NULL,

    CONSTRAINT pk_membro_vinculo PRIMARY KEY (id),

    CONSTRAINT fk_membro_vinculo_membro
        FOREIGN KEY (id_membro)
        REFERENCES membro(id),

    CONSTRAINT fk_membro_vinculo_funcao
        FOREIGN KEY (id_funcao)
        REFERENCES funcao(id),

    CONSTRAINT ck_membro_vinculo_periodo
        CHECK (
            data_termino IS NULL
            OR data_termino >= data_inicio
        )
);

CREATE UNIQUE INDEX uq_vinculo_ativo
  ON membro_vinculo (id_membro, id_funcao)
  WHERE data_termino IS NULL;


-- ============================================================================
-- TABELA DE RELACAO RESPONSAVEL
-- ============================================================================

CREATE TYPE tipo_relacao_responsavel AS ENUM ('PROGENITORES', 'AVO', 'PADRINHO', 'TIO', 'RESPONSAVEL_LEGAL');

CREATE TABLE IF NOT EXISTS membro_responsavel (
    id_responsavel UUID NOT NULL,
    id_membro_menor UUID NOT NULL,
    tipo_relacao tipo_relacao_responsavel NOT NULL,
    PRIMARY KEY (id_responsavel, id_membro_menor),
    CHECK (id_responsavel != id_membro_menor),
    FOREIGN KEY (id_responsavel) REFERENCES membro(id) ON DELETE CASCADE,
    FOREIGN KEY (id_membro_menor) REFERENCES membro(id) ON DELETE CASCADE
);

-- Tabela principal de músicas
CREATE TABLE IF NOT EXISTS musica (
    id UUID PRIMARY KEY,
    titulo VARCHAR(256) NOT NULL,
    compositor VARCHAR(256),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
 
-- Tabela de gêneros musicais
CREATE TABLE IF NOT EXISTS genero (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(256) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
 
-- Tabela de relacionamento: Uma música pode ter vários gêneros
CREATE TABLE IF NOT EXISTS genero_musica (
    id_musica UUID NOT NULL,
    id_genero INT NOT NULL,
    PRIMARY KEY (id_musica, id_genero),
    FOREIGN KEY (id_musica) REFERENCES musica(id) ON DELETE CASCADE,
    FOREIGN KEY (id_genero) REFERENCES genero(id) ON DELETE CASCADE
);
 
-- ============================================================================
-- TABELAS DE PARTITURAS
-- ============================================================================

-- Tabela de partituras (arranjos de músicas)
CREATE TABLE IF NOT EXISTS partitura (
    id UUID PRIMARY KEY,
    id_musica UUID NOT NULL,
    titulo VARCHAR(256) NOT NULL,
    arranjador VARCHAR(256),
    dificuldade INT NOT NULL,
    tipo_material_performance VARCHAR(256),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deletado_em TIMESTAMP,
    CHECK (dificuldade BETWEEN 1 AND 5),
    FOREIGN KEY (id_musica) REFERENCES musica(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_partitura_musica ON partitura(id_musica);

-- ============================================================================
-- TABELAS DE INSTRUMENTOS
-- ============================================================================
 
-- Tabela de instrumentos
CREATE TABLE IF NOT EXISTS instrumento (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(256) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
 
-- Tabela de relacionamento: Uma partitura pode ser para vários instrumentos
CREATE TABLE IF NOT EXISTS partitura_instrumento (
    id_partitura UUID NOT NULL,
    id_instrumento INT NOT NULL,
    PRIMARY KEY (id_partitura, id_instrumento),
    FOREIGN KEY (id_partitura) REFERENCES partitura(id) ON DELETE CASCADE,
    FOREIGN KEY (id_instrumento) REFERENCES instrumento(id) ON DELETE RESTRICT
);

-- o tipo "Aprendendo" é responsabilidade do backend e advém de uma regra negócio especifica.
-- Um membro esta aprendendo um instrumento se ele estiver matriculado em uma turma que tem esse instrumento.
 CREATE TYPE tipo_vinculo_instrumento AS ENUM ('DESEJA', 'TOCA');

-- Tabela de relacionamento: Um membro pode tocar vários instrumentos
CREATE TABLE IF NOT EXISTS instrumento_membro (
    id_membro UUID NOT NULL,
    id_instrumento INT NOT NULL,
    tipo_vinculo tipo_vinculo_instrumento NOT NULL,
    PRIMARY KEY (id_membro, id_instrumento),
    FOREIGN KEY (id_membro) REFERENCES membro(id),
    FOREIGN KEY (id_instrumento) REFERENCES instrumento(id)
);